export const countries = [
  { code: 'BR', name: 'Brasil', ddi: '+55' },
  { code: 'US', name: 'Estados Unidos', ddi: '+1' },
  { code: 'PT', name: 'Portugal', ddi: '+351' },
  { code: 'AR', name: 'Argentina', ddi: '+54' },
  { code: 'CL', name: 'Chile', ddi: '+56' },
  { code: 'CO', name: 'Colômbia', ddi: '+57' },
  { code: 'ES', name: 'Espanha', ddi: '+34' },
  { code: 'GB', name: 'Reino Unido', ddi: '+44' },
  { code: 'DE', name: 'Alemanha', ddi: '+49' },
  { code: 'FR', name: 'França', ddi: '+33' },
  { code: 'IT', name: 'Itália', ddi: '+39' },
  { code: 'CA', name: 'Canadá', ddi: '+1' },
  { code: 'MX', name: 'México', ddi: '+52' },
  { code: 'JP', name: 'Japão', ddi: '+81' },
  { code: 'UY', name: 'Uruguai', ddi: '+598' },
  { code: 'PY', name: 'Paraguai', ddi: '+595' },
  { code: 'PE', name: 'Peru', ddi: '+51' },
  { code: 'BO', name: 'Bolívia', ddi: '+591' },
  { code: 'EC', name: 'Equador', ddi: '+593' },
  { code: 'VE', name: 'Venezuela', ddi: '+58' },
  { code: 'AO', name: 'Angola', ddi: '+244' },
  { code: 'MZ', name: 'Moçambique', ddi: '+258' },
  { code: 'CN', name: 'China', ddi: '+86' },
  { code: 'IN', name: 'Índia', ddi: '+91' },
  { code: 'AU', name: 'Austrália', ddi: '+61' },
  { code: 'RU', name: 'Rússia', ddi: '+7' },
  { code: 'CH', name: 'Suíça', ddi: '+41' },
  { code: 'NL', name: 'Holanda', ddi: '+31' },
  { code: 'BE', name: 'Bélgica', ddi: '+32' },
  { code: 'SE', name: 'Suécia', ddi: '+46' },
  { code: 'NO', name: 'Noruega', ddi: '+47' },
  { code: 'DK', name: 'Dinamarca', ddi: '+45' },
  { code: 'FI', name: 'Finlândia', ddi: '+358' },
  { code: 'IE', name: 'Irlanda', ddi: '+353' },
  { code: 'AT', name: 'Áustria', ddi: '+43' },
  { code: 'NZ', name: 'Nova Zelândia', ddi: '+64' },
  { code: 'KR', name: 'Coreia do Sul', ddi: '+82' },
  { code: 'IL', name: 'Israel', ddi: '+972' },
  { code: 'AE', name: 'Emirados Árabes Unidos', ddi: '+971' },
  { code: 'SA', name: 'Arábia Saudita', ddi: '+966' },
  { code: 'TR', name: 'Turquia', ddi: '+90' },
  { code: 'ZA', name: 'África do Sul', ddi: '+27' },
];
