/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAffiliatesRouteImport } from './routes/_authenticated/affiliates'
import { Route as AuthenticatedCompleteProfileRouteImport } from './routes/_authenticated/complete-profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAffiliatesRouteImport } from './routes/_authenticated/admin/affiliates'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin/branding'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminCoolifyRouteImport } from './routes/_authenticated/admin/coolify'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated/admin/coupons'
import { Route as AuthenticatedAdminDatabaseRouteImport } from './routes/_authenticated/admin/database'
import { Route as AuthenticatedAdminDomainsRouteImport } from './routes/_authenticated/admin/domains'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin/emails'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin/import'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin/invoices'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminProductGroupsRouteImport } from './routes/_authenticated/admin/product-groups'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminServersRouteImport } from './routes/_authenticated/admin/servers'
import { Route as AuthenticatedAdminTicketsRouteImport } from './routes/_authenticated/admin/tickets'
import { Route as AuthenticatedAdminWhatsappRouteImport } from './routes/_authenticated/admin/whatsapp'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAppsAppIdRouteImport } from './routes/_authenticated/apps/$appId'
import { Route as AuthenticatedAppsCreateRouteImport } from './routes/_authenticated/apps/create'
import { Route as AuthenticatedDomainsIndexRouteImport } from './routes/_authenticated/domains.index'
import { Route as AuthenticatedDomainsDomainIdRouteImport } from './routes/_authenticated/domains.$domainId'
import { Route as AuthenticatedDomainsSearchRouteImport } from './routes/_authenticated/domains.search'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices.$invoiceId'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services.index'
import { Route as AuthenticatedServicesServiceIdRouteImport } from './routes/_authenticated/services.$serviceId'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets.index'
import { Route as AuthenticatedTicketsTicketIdRouteImport } from './routes/_authenticated/tickets.$ticketId'
import { Route as AuthenticatedVpsIndexRouteImport } from './routes/_authenticated/vps/index'
import { Route as AuthenticatedVpsVpsIdRouteImport } from './routes/_authenticated/vps/$vpsId'
import { Route as ApiFileManagerUploadRouteImport } from './routes/api/file-manager/upload'
import { Route as ApiPublicBrandingRouteImport } from './routes/api/public/branding'
import { Route as ApiPublicPasswordResetRouteImport } from './routes/api/public/password-reset'
import { Route as ApiPublicVpsMetricsRouteImport } from './routes/api/public/vps-metrics'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public/webhook'
import { Route as AuthenticatedAdminClientsIndexRouteImport } from './routes/_authenticated/admin/clients.index'
import { Route as AuthenticatedAdminClientsClientIdRouteImport } from './routes/_authenticated/admin/clients.$clientId'
import { Route as AuthenticatedAdminVpsIndexRouteImport } from './routes/_authenticated/admin/vps/index'
import { Route as AuthenticatedAdminVpsPlansRouteImport } from './routes/_authenticated/admin/vps/plans'
import { Route as ApiFileManagerBundleAppIdRouteImport } from './routes/api/file-manager/bundle/$appId'
import { Route as ApiFileManagerJobsJobIdRouteImport } from './routes/api/file-manager/jobs/$jobId'
import { Route as ApiFileManagerJobsCompressRouteImport } from './routes/api/file-manager/jobs/compress'
import { Route as ApiFileManagerJobsExtractRouteImport } from './routes/api/file-manager/jobs/extract'
import { Route as ApiPublicCronMaintenanceRouteImport } from './routes/api/public/cron/maintenance'
import { Route as ApiPublicScriptsInstallAgentRouteImport } from './routes/api/public/scripts/install-agent'
import { Route as ApiPublicScriptsUninstallAgentRouteImport } from './routes/api/public/scripts/uninstall-agent'
import { Route as ApiPublicVpsWebhookRouteImport } from './routes/api/public/vps/webhook'
import { Route as ApiPublicWebhooksAbacatepayRouteImport } from './routes/api/public/webhooks/abacatepay'
import { Route as ApiPublicWebhooksCajupayRouteImport } from './routes/api/public/webhooks/cajupay'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as ApiPublicWebhooksPaghiperRouteImport } from './routes/api/public/webhooks/paghiper'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicWebhooksWooviRouteImport } from './routes/api/public/webhooks/woovi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAffiliatesRoute = AuthenticatedAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteProfileRoute =
  AuthenticatedCompleteProfileRouteImport.update({
    id: '/complete-profile',
    path: '/complete-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAffiliatesRoute =
  AuthenticatedAdminAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoolifyRoute =
  AuthenticatedAdminCoolifyRouteImport.update({
    id: '/coolify',
    path: '/coolify',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDatabaseRoute =
  AuthenticatedAdminDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDomainsRoute =
  AuthenticatedAdminDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProductGroupsRoute =
  AuthenticatedAdminProductGroupsRouteImport.update({
    id: '/product-groups',
    path: '/product-groups',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminServersRoute =
  AuthenticatedAdminServersRouteImport.update({
    id: '/servers',
    path: '/servers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTicketsRoute =
  AuthenticatedAdminTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWhatsappRoute =
  AuthenticatedAdminWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsAppIdRoute = AuthenticatedAppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsCreateRoute = AuthenticatedAppsCreateRouteImport.update({
  id: '/apps/create',
  path: '/apps/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomainsIndexRoute =
  AuthenticatedDomainsIndexRouteImport.update({
    id: '/domains/',
    path: '/domains/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDomainsDomainIdRoute =
  AuthenticatedDomainsDomainIdRouteImport.update({
    id: '/domains/$domainId',
    path: '/domains/$domainId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDomainsSearchRoute =
  AuthenticatedDomainsSearchRouteImport.update({
    id: '/domains/search',
    path: '/domains/search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedServicesRoute,
  } as any)
const AuthenticatedServicesServiceIdRoute =
  AuthenticatedServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => AuthenticatedServicesRoute,
  } as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTicketsRoute,
  } as any)
const AuthenticatedTicketsTicketIdRoute =
  AuthenticatedTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AuthenticatedTicketsRoute,
  } as any)
const AuthenticatedVpsIndexRoute = AuthenticatedVpsIndexRouteImport.update({
  id: '/vps/',
  path: '/vps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVpsVpsIdRoute = AuthenticatedVpsVpsIdRouteImport.update({
  id: '/vps/$vpsId',
  path: '/vps/$vpsId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiFileManagerUploadRoute = ApiFileManagerUploadRouteImport.update({
  id: '/api/file-manager/upload',
  path: '/api/file-manager/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandingRoute = ApiPublicBrandingRouteImport.update({
  id: '/api/public/branding',
  path: '/api/public/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPasswordResetRoute = ApiPublicPasswordResetRouteImport.update({
  id: '/api/public/password-reset',
  path: '/api/public/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVpsMetricsRoute = ApiPublicVpsMetricsRouteImport.update({
  id: '/api/public/vps-metrics',
  path: '/api/public/vps-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminClientsIndexRoute =
  AuthenticatedAdminClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminClientsClientIdRoute =
  AuthenticatedAdminClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminVpsIndexRoute =
  AuthenticatedAdminVpsIndexRouteImport.update({
    id: '/vps/',
    path: '/vps/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVpsPlansRoute =
  AuthenticatedAdminVpsPlansRouteImport.update({
    id: '/vps/plans',
    path: '/vps/plans',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiFileManagerBundleAppIdRoute =
  ApiFileManagerBundleAppIdRouteImport.update({
    id: '/api/file-manager/bundle/$appId',
    path: '/api/file-manager/bundle/$appId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFileManagerJobsJobIdRoute = ApiFileManagerJobsJobIdRouteImport.update({
  id: '/api/file-manager/jobs/$jobId',
  path: '/api/file-manager/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileManagerJobsCompressRoute =
  ApiFileManagerJobsCompressRouteImport.update({
    id: '/api/file-manager/jobs/compress',
    path: '/api/file-manager/jobs/compress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFileManagerJobsExtractRoute =
  ApiFileManagerJobsExtractRouteImport.update({
    id: '/api/file-manager/jobs/extract',
    path: '/api/file-manager/jobs/extract',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMaintenanceRoute =
  ApiPublicCronMaintenanceRouteImport.update({
    id: '/api/public/cron/maintenance',
    path: '/api/public/cron/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScriptsInstallAgentRoute =
  ApiPublicScriptsInstallAgentRouteImport.update({
    id: '/api/public/scripts/install-agent',
    path: '/api/public/scripts/install-agent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScriptsUninstallAgentRoute =
  ApiPublicScriptsUninstallAgentRouteImport.update({
    id: '/api/public/scripts/uninstall-agent',
    path: '/api/public/scripts/uninstall-agent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVpsWebhookRoute = ApiPublicVpsWebhookRouteImport.update({
  id: '/api/public/vps/webhook',
  path: '/api/public/vps/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksAbacatepayRoute =
  ApiPublicWebhooksAbacatepayRouteImport.update({
    id: '/api/public/webhooks/abacatepay',
    path: '/api/public/webhooks/abacatepay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksCajupayRoute =
  ApiPublicWebhooksCajupayRouteImport.update({
    id: '/api/public/webhooks/cajupay',
    path: '/api/public/webhooks/cajupay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPaghiperRoute =
  ApiPublicWebhooksPaghiperRouteImport.update({
    id: '/api/public/webhooks/paghiper',
    path: '/api/public/webhooks/paghiper',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksWooviRoute = ApiPublicWebhooksWooviRouteImport.update({
  id: '/api/public/webhooks/woovi',
  path: '/api/public/webhooks/woovi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/affiliates': typeof AuthenticatedAffiliatesRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/services': typeof AuthenticatedServicesRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/wallet': typeof AuthenticatedWalletRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/coolify': typeof AuthenticatedAdminCoolifyRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/database': typeof AuthenticatedAdminDatabaseRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/product-groups': typeof AuthenticatedAdminProductGroupsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/servers': typeof AuthenticatedAdminServersRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/apps/$appId': typeof AuthenticatedAppsAppIdRoute
  '/apps/create': typeof AuthenticatedAppsCreateRoute
  '/domains/$domainId': typeof AuthenticatedDomainsDomainIdRoute
  '/domains/search': typeof AuthenticatedDomainsSearchRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/vps/$vpsId': typeof AuthenticatedVpsVpsIdRoute
  '/api/file-manager/upload': typeof ApiFileManagerUploadRoute
  '/api/public/branding': typeof ApiPublicBrandingRoute
  '/api/public/password-reset': typeof ApiPublicPasswordResetRoute
  '/api/public/vps-metrics': typeof ApiPublicVpsMetricsRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/domains/': typeof AuthenticatedDomainsIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/vps/': typeof AuthenticatedVpsIndexRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/admin/vps/plans': typeof AuthenticatedAdminVpsPlansRoute
  '/api/file-manager/bundle/$appId': typeof ApiFileManagerBundleAppIdRoute
  '/api/file-manager/jobs/$jobId': typeof ApiFileManagerJobsJobIdRoute
  '/api/file-manager/jobs/compress': typeof ApiFileManagerJobsCompressRoute
  '/api/file-manager/jobs/extract': typeof ApiFileManagerJobsExtractRoute
  '/api/public/cron/maintenance': typeof ApiPublicCronMaintenanceRoute
  '/api/public/scripts/install-agent': typeof ApiPublicScriptsInstallAgentRoute
  '/api/public/scripts/uninstall-agent': typeof ApiPublicScriptsUninstallAgentRoute
  '/api/public/vps/webhook': typeof ApiPublicVpsWebhookRoute
  '/api/public/webhooks/abacatepay': typeof ApiPublicWebhooksAbacatepayRoute
  '/api/public/webhooks/cajupay': typeof ApiPublicWebhooksCajupayRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/paghiper': typeof ApiPublicWebhooksPaghiperRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/woovi': typeof ApiPublicWebhooksWooviRoute
  '/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/vps/': typeof AuthenticatedAdminVpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/affiliates': typeof AuthenticatedAffiliatesRoute
  '/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/coolify': typeof AuthenticatedAdminCoolifyRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/database': typeof AuthenticatedAdminDatabaseRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/product-groups': typeof AuthenticatedAdminProductGroupsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/servers': typeof AuthenticatedAdminServersRoute
  '/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/apps/$appId': typeof AuthenticatedAppsAppIdRoute
  '/apps/create': typeof AuthenticatedAppsCreateRoute
  '/domains/$domainId': typeof AuthenticatedDomainsDomainIdRoute
  '/domains/search': typeof AuthenticatedDomainsSearchRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/vps/$vpsId': typeof AuthenticatedVpsVpsIdRoute
  '/api/file-manager/upload': typeof ApiFileManagerUploadRoute
  '/api/public/branding': typeof ApiPublicBrandingRoute
  '/api/public/password-reset': typeof ApiPublicPasswordResetRoute
  '/api/public/vps-metrics': typeof ApiPublicVpsMetricsRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/domains': typeof AuthenticatedDomainsIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/vps': typeof AuthenticatedVpsIndexRoute
  '/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/admin/vps/plans': typeof AuthenticatedAdminVpsPlansRoute
  '/api/file-manager/bundle/$appId': typeof ApiFileManagerBundleAppIdRoute
  '/api/file-manager/jobs/$jobId': typeof ApiFileManagerJobsJobIdRoute
  '/api/file-manager/jobs/compress': typeof ApiFileManagerJobsCompressRoute
  '/api/file-manager/jobs/extract': typeof ApiFileManagerJobsExtractRoute
  '/api/public/cron/maintenance': typeof ApiPublicCronMaintenanceRoute
  '/api/public/scripts/install-agent': typeof ApiPublicScriptsInstallAgentRoute
  '/api/public/scripts/uninstall-agent': typeof ApiPublicScriptsUninstallAgentRoute
  '/api/public/vps/webhook': typeof ApiPublicVpsWebhookRoute
  '/api/public/webhooks/abacatepay': typeof ApiPublicWebhooksAbacatepayRoute
  '/api/public/webhooks/cajupay': typeof ApiPublicWebhooksCajupayRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/paghiper': typeof ApiPublicWebhooksPaghiperRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/woovi': typeof ApiPublicWebhooksWooviRoute
  '/admin/clients': typeof AuthenticatedAdminClientsIndexRoute
  '/admin/vps': typeof AuthenticatedAdminVpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/affiliates': typeof AuthenticatedAffiliatesRoute
  '/_authenticated/complete-profile': typeof AuthenticatedCompleteProfileRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/services': typeof AuthenticatedServicesRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/_authenticated/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/coolify': typeof AuthenticatedAdminCoolifyRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/database': typeof AuthenticatedAdminDatabaseRoute
  '/_authenticated/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/product-groups': typeof AuthenticatedAdminProductGroupsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/servers': typeof AuthenticatedAdminServersRoute
  '/_authenticated/admin/tickets': typeof AuthenticatedAdminTicketsRoute
  '/_authenticated/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/_authenticated/apps/$appId': typeof AuthenticatedAppsAppIdRoute
  '/_authenticated/apps/create': typeof AuthenticatedAppsCreateRoute
  '/_authenticated/domains/$domainId': typeof AuthenticatedDomainsDomainIdRoute
  '/_authenticated/domains/search': typeof AuthenticatedDomainsSearchRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/_authenticated/tickets/$ticketId': typeof AuthenticatedTicketsTicketIdRoute
  '/_authenticated/vps/$vpsId': typeof AuthenticatedVpsVpsIdRoute
  '/api/file-manager/upload': typeof ApiFileManagerUploadRoute
  '/api/public/branding': typeof ApiPublicBrandingRoute
  '/api/public/password-reset': typeof ApiPublicPasswordResetRoute
  '/api/public/vps-metrics': typeof ApiPublicVpsMetricsRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/domains/': typeof AuthenticatedDomainsIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/vps/': typeof AuthenticatedVpsIndexRoute
  '/_authenticated/admin/clients/$clientId': typeof AuthenticatedAdminClientsClientIdRoute
  '/_authenticated/admin/vps/plans': typeof AuthenticatedAdminVpsPlansRoute
  '/api/file-manager/bundle/$appId': typeof ApiFileManagerBundleAppIdRoute
  '/api/file-manager/jobs/$jobId': typeof ApiFileManagerJobsJobIdRoute
  '/api/file-manager/jobs/compress': typeof ApiFileManagerJobsCompressRoute
  '/api/file-manager/jobs/extract': typeof ApiFileManagerJobsExtractRoute
  '/api/public/cron/maintenance': typeof ApiPublicCronMaintenanceRoute
  '/api/public/scripts/install-agent': typeof ApiPublicScriptsInstallAgentRoute
  '/api/public/scripts/uninstall-agent': typeof ApiPublicScriptsUninstallAgentRoute
  '/api/public/vps/webhook': typeof ApiPublicVpsWebhookRoute
  '/api/public/webhooks/abacatepay': typeof ApiPublicWebhooksAbacatepayRoute
  '/api/public/webhooks/cajupay': typeof ApiPublicWebhooksCajupayRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/api/public/webhooks/paghiper': typeof ApiPublicWebhooksPaghiperRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/woovi': typeof ApiPublicWebhooksWooviRoute
  '/_authenticated/admin/clients/': typeof AuthenticatedAdminClientsIndexRoute
  '/_authenticated/admin/vps/': typeof AuthenticatedAdminVpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/affiliates'
    | '/complete-profile'
    | '/dashboard'
    | '/invoices'
    | '/plans'
    | '/profile'
    | '/services'
    | '/tickets'
    | '/wallet'
    | '/auth/reset-password'
    | '/checkout/$productId'
    | '/admin/affiliates'
    | '/admin/branding'
    | '/admin/clients'
    | '/admin/coolify'
    | '/admin/coupons'
    | '/admin/database'
    | '/admin/domains'
    | '/admin/emails'
    | '/admin/finance'
    | '/admin/import'
    | '/admin/invoices'
    | '/admin/logs'
    | '/admin/product-groups'
    | '/admin/products'
    | '/admin/servers'
    | '/admin/tickets'
    | '/admin/whatsapp'
    | '/apps/$appId'
    | '/apps/create'
    | '/domains/$domainId'
    | '/domains/search'
    | '/invoices/$invoiceId'
    | '/services/$serviceId'
    | '/tickets/$ticketId'
    | '/vps/$vpsId'
    | '/api/file-manager/upload'
    | '/api/public/branding'
    | '/api/public/password-reset'
    | '/api/public/vps-metrics'
    | '/api/public/webhook'
    | '/admin/'
    | '/apps/'
    | '/domains/'
    | '/invoices/'
    | '/services/'
    | '/tickets/'
    | '/vps/'
    | '/admin/clients/$clientId'
    | '/admin/vps/plans'
    | '/api/file-manager/bundle/$appId'
    | '/api/file-manager/jobs/$jobId'
    | '/api/file-manager/jobs/compress'
    | '/api/file-manager/jobs/extract'
    | '/api/public/cron/maintenance'
    | '/api/public/scripts/install-agent'
    | '/api/public/scripts/uninstall-agent'
    | '/api/public/vps/webhook'
    | '/api/public/webhooks/abacatepay'
    | '/api/public/webhooks/cajupay'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/paghiper'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/woovi'
    | '/admin/clients/'
    | '/admin/vps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/affiliates'
    | '/complete-profile'
    | '/dashboard'
    | '/plans'
    | '/profile'
    | '/wallet'
    | '/auth/reset-password'
    | '/checkout/$productId'
    | '/admin/affiliates'
    | '/admin/branding'
    | '/admin/coolify'
    | '/admin/coupons'
    | '/admin/database'
    | '/admin/domains'
    | '/admin/emails'
    | '/admin/finance'
    | '/admin/import'
    | '/admin/invoices'
    | '/admin/logs'
    | '/admin/product-groups'
    | '/admin/products'
    | '/admin/servers'
    | '/admin/tickets'
    | '/admin/whatsapp'
    | '/apps/$appId'
    | '/apps/create'
    | '/domains/$domainId'
    | '/domains/search'
    | '/invoices/$invoiceId'
    | '/services/$serviceId'
    | '/tickets/$ticketId'
    | '/vps/$vpsId'
    | '/api/file-manager/upload'
    | '/api/public/branding'
    | '/api/public/password-reset'
    | '/api/public/vps-metrics'
    | '/api/public/webhook'
    | '/admin'
    | '/apps'
    | '/domains'
    | '/invoices'
    | '/services'
    | '/tickets'
    | '/vps'
    | '/admin/clients/$clientId'
    | '/admin/vps/plans'
    | '/api/file-manager/bundle/$appId'
    | '/api/file-manager/jobs/$jobId'
    | '/api/file-manager/jobs/compress'
    | '/api/file-manager/jobs/extract'
    | '/api/public/cron/maintenance'
    | '/api/public/scripts/install-agent'
    | '/api/public/scripts/uninstall-agent'
    | '/api/public/vps/webhook'
    | '/api/public/webhooks/abacatepay'
    | '/api/public/webhooks/cajupay'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/paghiper'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/woovi'
    | '/admin/clients'
    | '/admin/vps'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/affiliates'
    | '/_authenticated/complete-profile'
    | '/_authenticated/dashboard'
    | '/_authenticated/invoices'
    | '/_authenticated/plans'
    | '/_authenticated/profile'
    | '/_authenticated/services'
    | '/_authenticated/tickets'
    | '/_authenticated/wallet'
    | '/auth/reset-password'
    | '/checkout/$productId'
    | '/_authenticated/admin/affiliates'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/coolify'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/database'
    | '/_authenticated/admin/domains'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/product-groups'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/servers'
    | '/_authenticated/admin/tickets'
    | '/_authenticated/admin/whatsapp'
    | '/_authenticated/apps/$appId'
    | '/_authenticated/apps/create'
    | '/_authenticated/domains/$domainId'
    | '/_authenticated/domains/search'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/services/$serviceId'
    | '/_authenticated/tickets/$ticketId'
    | '/_authenticated/vps/$vpsId'
    | '/api/file-manager/upload'
    | '/api/public/branding'
    | '/api/public/password-reset'
    | '/api/public/vps-metrics'
    | '/api/public/webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/apps/'
    | '/_authenticated/domains/'
    | '/_authenticated/invoices/'
    | '/_authenticated/services/'
    | '/_authenticated/tickets/'
    | '/_authenticated/vps/'
    | '/_authenticated/admin/clients/$clientId'
    | '/_authenticated/admin/vps/plans'
    | '/api/file-manager/bundle/$appId'
    | '/api/file-manager/jobs/$jobId'
    | '/api/file-manager/jobs/compress'
    | '/api/file-manager/jobs/extract'
    | '/api/public/cron/maintenance'
    | '/api/public/scripts/install-agent'
    | '/api/public/scripts/uninstall-agent'
    | '/api/public/vps/webhook'
    | '/api/public/webhooks/abacatepay'
    | '/api/public/webhooks/cajupay'
    | '/api/public/webhooks/mercadopago'
    | '/api/public/webhooks/paghiper'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/woovi'
    | '/_authenticated/admin/clients/'
    | '/_authenticated/admin/vps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  ApiFileManagerUploadRoute: typeof ApiFileManagerUploadRoute
  ApiPublicBrandingRoute: typeof ApiPublicBrandingRoute
  ApiPublicPasswordResetRoute: typeof ApiPublicPasswordResetRoute
  ApiPublicVpsMetricsRoute: typeof ApiPublicVpsMetricsRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
  ApiFileManagerBundleAppIdRoute: typeof ApiFileManagerBundleAppIdRoute
  ApiFileManagerJobsJobIdRoute: typeof ApiFileManagerJobsJobIdRoute
  ApiFileManagerJobsCompressRoute: typeof ApiFileManagerJobsCompressRoute
  ApiFileManagerJobsExtractRoute: typeof ApiFileManagerJobsExtractRoute
  ApiPublicCronMaintenanceRoute: typeof ApiPublicCronMaintenanceRoute
  ApiPublicScriptsInstallAgentRoute: typeof ApiPublicScriptsInstallAgentRoute
  ApiPublicScriptsUninstallAgentRoute: typeof ApiPublicScriptsUninstallAgentRoute
  ApiPublicVpsWebhookRoute: typeof ApiPublicVpsWebhookRoute
  ApiPublicWebhooksAbacatepayRoute: typeof ApiPublicWebhooksAbacatepayRoute
  ApiPublicWebhooksCajupayRoute: typeof ApiPublicWebhooksCajupayRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
  ApiPublicWebhooksPaghiperRoute: typeof ApiPublicWebhooksPaghiperRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiPublicWebhooksWooviRoute: typeof ApiPublicWebhooksWooviRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/affiliates': {
      id: '/_authenticated/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AuthenticatedAffiliatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-profile': {
      id: '/_authenticated/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthenticatedCompleteProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/affiliates': {
      id: '/_authenticated/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AuthenticatedAdminAffiliatesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coolify': {
      id: '/_authenticated/admin/coolify'
      path: '/coolify'
      fullPath: '/admin/coolify'
      preLoaderRoute: typeof AuthenticatedAdminCoolifyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/database': {
      id: '/_authenticated/admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AuthenticatedAdminDatabaseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/domains': {
      id: '/_authenticated/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AuthenticatedAdminDomainsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/product-groups': {
      id: '/_authenticated/admin/product-groups'
      path: '/product-groups'
      fullPath: '/admin/product-groups'
      preLoaderRoute: typeof AuthenticatedAdminProductGroupsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/servers': {
      id: '/_authenticated/admin/servers'
      path: '/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof AuthenticatedAdminServersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tickets': {
      id: '/_authenticated/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AuthenticatedAdminTicketsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/whatsapp': {
      id: '/_authenticated/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/$appId': {
      id: '/_authenticated/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AuthenticatedAppsAppIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/create': {
      id: '/_authenticated/apps/create'
      path: '/apps/create'
      fullPath: '/apps/create'
      preLoaderRoute: typeof AuthenticatedAppsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains/': {
      id: '/_authenticated/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof AuthenticatedDomainsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains/$domainId': {
      id: '/_authenticated/domains/$domainId'
      path: '/domains/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof AuthenticatedDomainsDomainIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains/search': {
      id: '/_authenticated/domains/search'
      path: '/domains/search'
      fullPath: '/domains/search'
      preLoaderRoute: typeof AuthenticatedDomainsSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedServicesRoute
    }
    '/_authenticated/services/$serviceId': {
      id: '/_authenticated/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedServicesServiceIdRouteImport
      parentRoute: typeof AuthenticatedServicesRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/tickets/$ticketId': {
      id: '/_authenticated/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/_authenticated/vps/': {
      id: '/_authenticated/vps/'
      path: '/vps'
      fullPath: '/vps/'
      preLoaderRoute: typeof AuthenticatedVpsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vps/$vpsId': {
      id: '/_authenticated/vps/$vpsId'
      path: '/vps/$vpsId'
      fullPath: '/vps/$vpsId'
      preLoaderRoute: typeof AuthenticatedVpsVpsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/file-manager/upload': {
      id: '/api/file-manager/upload'
      path: '/api/file-manager/upload'
      fullPath: '/api/file-manager/upload'
      preLoaderRoute: typeof ApiFileManagerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/branding': {
      id: '/api/public/branding'
      path: '/api/public/branding'
      fullPath: '/api/public/branding'
      preLoaderRoute: typeof ApiPublicBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/password-reset': {
      id: '/api/public/password-reset'
      path: '/api/public/password-reset'
      fullPath: '/api/public/password-reset'
      preLoaderRoute: typeof ApiPublicPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vps-metrics': {
      id: '/api/public/vps-metrics'
      path: '/api/public/vps-metrics'
      fullPath: '/api/public/vps-metrics'
      preLoaderRoute: typeof ApiPublicVpsMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/clients/': {
      id: '/_authenticated/admin/clients/'
      path: '/'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AuthenticatedAdminClientsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/clients/$clientId': {
      id: '/_authenticated/admin/clients/$clientId'
      path: '/$clientId'
      fullPath: '/admin/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedAdminClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/vps/': {
      id: '/_authenticated/admin/vps/'
      path: '/vps'
      fullPath: '/admin/vps/'
      preLoaderRoute: typeof AuthenticatedAdminVpsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/vps/plans': {
      id: '/_authenticated/admin/vps/plans'
      path: '/vps/plans'
      fullPath: '/admin/vps/plans'
      preLoaderRoute: typeof AuthenticatedAdminVpsPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/file-manager/bundle/$appId': {
      id: '/api/file-manager/bundle/$appId'
      path: '/api/file-manager/bundle/$appId'
      fullPath: '/api/file-manager/bundle/$appId'
      preLoaderRoute: typeof ApiFileManagerBundleAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-manager/jobs/$jobId': {
      id: '/api/file-manager/jobs/$jobId'
      path: '/api/file-manager/jobs/$jobId'
      fullPath: '/api/file-manager/jobs/$jobId'
      preLoaderRoute: typeof ApiFileManagerJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-manager/jobs/compress': {
      id: '/api/file-manager/jobs/compress'
      path: '/api/file-manager/jobs/compress'
      fullPath: '/api/file-manager/jobs/compress'
      preLoaderRoute: typeof ApiFileManagerJobsCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file-manager/jobs/extract': {
      id: '/api/file-manager/jobs/extract'
      path: '/api/file-manager/jobs/extract'
      fullPath: '/api/file-manager/jobs/extract'
      preLoaderRoute: typeof ApiFileManagerJobsExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/maintenance': {
      id: '/api/public/cron/maintenance'
      path: '/api/public/cron/maintenance'
      fullPath: '/api/public/cron/maintenance'
      preLoaderRoute: typeof ApiPublicCronMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scripts/install-agent': {
      id: '/api/public/scripts/install-agent'
      path: '/api/public/scripts/install-agent'
      fullPath: '/api/public/scripts/install-agent'
      preLoaderRoute: typeof ApiPublicScriptsInstallAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scripts/uninstall-agent': {
      id: '/api/public/scripts/uninstall-agent'
      path: '/api/public/scripts/uninstall-agent'
      fullPath: '/api/public/scripts/uninstall-agent'
      preLoaderRoute: typeof ApiPublicScriptsUninstallAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vps/webhook': {
      id: '/api/public/vps/webhook'
      path: '/api/public/vps/webhook'
      fullPath: '/api/public/vps/webhook'
      preLoaderRoute: typeof ApiPublicVpsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/abacatepay': {
      id: '/api/public/webhooks/abacatepay'
      path: '/api/public/webhooks/abacatepay'
      fullPath: '/api/public/webhooks/abacatepay'
      preLoaderRoute: typeof ApiPublicWebhooksAbacatepayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/cajupay': {
      id: '/api/public/webhooks/cajupay'
      path: '/api/public/webhooks/cajupay'
      fullPath: '/api/public/webhooks/cajupay'
      preLoaderRoute: typeof ApiPublicWebhooksCajupayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paghiper': {
      id: '/api/public/webhooks/paghiper'
      path: '/api/public/webhooks/paghiper'
      fullPath: '/api/public/webhooks/paghiper'
      preLoaderRoute: typeof ApiPublicWebhooksPaghiperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/woovi': {
      id: '/api/public/webhooks/woovi'
      path: '/api/public/webhooks/woovi'
      fullPath: '/api/public/webhooks/woovi'
      preLoaderRoute: typeof ApiPublicWebhooksWooviRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsClientIdRoute: typeof AuthenticatedAdminClientsClientIdRoute
  AuthenticatedAdminClientsIndexRoute: typeof AuthenticatedAdminClientsIndexRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsClientIdRoute:
      AuthenticatedAdminClientsClientIdRoute,
    AuthenticatedAdminClientsIndexRoute: AuthenticatedAdminClientsIndexRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAffiliatesRoute: typeof AuthenticatedAdminAffiliatesRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminCoolifyRoute: typeof AuthenticatedAdminCoolifyRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminDatabaseRoute: typeof AuthenticatedAdminDatabaseRoute
  AuthenticatedAdminDomainsRoute: typeof AuthenticatedAdminDomainsRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminProductGroupsRoute: typeof AuthenticatedAdminProductGroupsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminServersRoute: typeof AuthenticatedAdminServersRoute
  AuthenticatedAdminTicketsRoute: typeof AuthenticatedAdminTicketsRoute
  AuthenticatedAdminWhatsappRoute: typeof AuthenticatedAdminWhatsappRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminVpsPlansRoute: typeof AuthenticatedAdminVpsPlansRoute
  AuthenticatedAdminVpsIndexRoute: typeof AuthenticatedAdminVpsIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAffiliatesRoute: AuthenticatedAdminAffiliatesRoute,
    AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
    AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
    AuthenticatedAdminCoolifyRoute: AuthenticatedAdminCoolifyRoute,
    AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
    AuthenticatedAdminDatabaseRoute: AuthenticatedAdminDatabaseRoute,
    AuthenticatedAdminDomainsRoute: AuthenticatedAdminDomainsRoute,
    AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
    AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
    AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
    AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
    AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
    AuthenticatedAdminProductGroupsRoute: AuthenticatedAdminProductGroupsRoute,
    AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
    AuthenticatedAdminServersRoute: AuthenticatedAdminServersRoute,
    AuthenticatedAdminTicketsRoute: AuthenticatedAdminTicketsRoute,
    AuthenticatedAdminWhatsappRoute: AuthenticatedAdminWhatsappRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminVpsPlansRoute: AuthenticatedAdminVpsPlansRoute,
    AuthenticatedAdminVpsIndexRoute: AuthenticatedAdminVpsIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedServicesRouteChildren {
  AuthenticatedServicesServiceIdRoute: typeof AuthenticatedServicesServiceIdRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
}

const AuthenticatedServicesRouteChildren: AuthenticatedServicesRouteChildren = {
  AuthenticatedServicesServiceIdRoute: AuthenticatedServicesServiceIdRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
}

const AuthenticatedServicesRouteWithChildren =
  AuthenticatedServicesRoute._addFileChildren(
    AuthenticatedServicesRouteChildren,
  )

interface AuthenticatedTicketsRouteChildren {
  AuthenticatedTicketsTicketIdRoute: typeof AuthenticatedTicketsTicketIdRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
}

const AuthenticatedTicketsRouteChildren: AuthenticatedTicketsRouteChildren = {
  AuthenticatedTicketsTicketIdRoute: AuthenticatedTicketsTicketIdRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
}

const AuthenticatedTicketsRouteWithChildren =
  AuthenticatedTicketsRoute._addFileChildren(AuthenticatedTicketsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAffiliatesRoute: typeof AuthenticatedAffiliatesRoute
  AuthenticatedCompleteProfileRoute: typeof AuthenticatedCompleteProfileRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRouteWithChildren
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRouteWithChildren
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedAppsAppIdRoute: typeof AuthenticatedAppsAppIdRoute
  AuthenticatedAppsCreateRoute: typeof AuthenticatedAppsCreateRoute
  AuthenticatedDomainsDomainIdRoute: typeof AuthenticatedDomainsDomainIdRoute
  AuthenticatedDomainsSearchRoute: typeof AuthenticatedDomainsSearchRoute
  AuthenticatedVpsVpsIdRoute: typeof AuthenticatedVpsVpsIdRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedDomainsIndexRoute: typeof AuthenticatedDomainsIndexRoute
  AuthenticatedVpsIndexRoute: typeof AuthenticatedVpsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAffiliatesRoute: AuthenticatedAffiliatesRoute,
  AuthenticatedCompleteProfileRoute: AuthenticatedCompleteProfileRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRouteWithChildren,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRouteWithChildren,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedAppsAppIdRoute: AuthenticatedAppsAppIdRoute,
  AuthenticatedAppsCreateRoute: AuthenticatedAppsCreateRoute,
  AuthenticatedDomainsDomainIdRoute: AuthenticatedDomainsDomainIdRoute,
  AuthenticatedDomainsSearchRoute: AuthenticatedDomainsSearchRoute,
  AuthenticatedVpsVpsIdRoute: AuthenticatedVpsVpsIdRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedDomainsIndexRoute: AuthenticatedDomainsIndexRoute,
  AuthenticatedVpsIndexRoute: AuthenticatedVpsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  ApiFileManagerUploadRoute: ApiFileManagerUploadRoute,
  ApiPublicBrandingRoute: ApiPublicBrandingRoute,
  ApiPublicPasswordResetRoute: ApiPublicPasswordResetRoute,
  ApiPublicVpsMetricsRoute: ApiPublicVpsMetricsRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
  ApiFileManagerBundleAppIdRoute: ApiFileManagerBundleAppIdRoute,
  ApiFileManagerJobsJobIdRoute: ApiFileManagerJobsJobIdRoute,
  ApiFileManagerJobsCompressRoute: ApiFileManagerJobsCompressRoute,
  ApiFileManagerJobsExtractRoute: ApiFileManagerJobsExtractRoute,
  ApiPublicCronMaintenanceRoute: ApiPublicCronMaintenanceRoute,
  ApiPublicScriptsInstallAgentRoute: ApiPublicScriptsInstallAgentRoute,
  ApiPublicScriptsUninstallAgentRoute: ApiPublicScriptsUninstallAgentRoute,
  ApiPublicVpsWebhookRoute: ApiPublicVpsWebhookRoute,
  ApiPublicWebhooksAbacatepayRoute: ApiPublicWebhooksAbacatepayRoute,
  ApiPublicWebhooksCajupayRoute: ApiPublicWebhooksCajupayRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
  ApiPublicWebhooksPaghiperRoute: ApiPublicWebhooksPaghiperRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiPublicWebhooksWooviRoute: ApiPublicWebhooksWooviRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
